name: imagebox

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  exifdart:

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  build_daemon: '>=1.0.0 <2.0.0'
  pedantic: ^1.8.0
